// src/assets/img/images.ts
const images = {
  appointmentEmpty: require('./appointment-empty.png'),
  appointmentFilled: require('./appointment-filled.png'),
  avatar: require('./avatar.jpg'),
  back: require('./back.png'),
  calendar: require('./calendar.png'),
  chat: require('./chat.png'),
  clock: require('./clock.png'),
  doctor: require('./doctor.png'),
  facility: require('./facility.png'),
  googleIcon: require('./google_icon.png'),
  homeEmpty: require('./home-empty.png'),
  homeFilled: require('./home-filled.png'),
  icon: require('./icon.png'),
  like: require('./like.png'),
  profileEmpty: require('./ProfileEmpty.png'),
  profileFilled: require('./ProfileFilled.png'),
  rating: require('./rating.png'),
  search: require('./search.png'),
  settingFilled: require('./setting-filled.png'),
  settings: require('./settings.png'),
  splash: require('./splash.png'),
  star: require('./star.png'),
  trend: require('./trend.png'),
  users: require('./users.png'),
  search2: require("./search2.png"),
  back_white:require("./back-white.png"),
  call:require("./call.png"),
  mic_mute:require("./mic_mute.png"),
  speaker:require('./speaker.png'),
  end_call:require("./end_call.png"),
  green_call:require("./green_call.png"),
  red_call:require('./red_call.png'),

};

export default images;
